spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true
    redis:
      uri: ${REDIS_URI}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: prod

server:
  port: ${PORT:8080}
  #servlet:
   # context-path: /journal